Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    
    config.vm.provision "shell", inline: "sudo echo TestPassword | passwd root --stdin"
    config.vm.provision "shell", inline: "adduser db_user"
    config.vm.provision "shell", inline: "sudo echo TestPassword | passwd db_user --stdin"
    config.vm.provision "shell", inline: "echo LC_CTYPE=en_US.UTF-8 >>  /etc/environment  "
    config.vm.provision "shell", inline: "
    echo '
    #Este es mi server Base de Datos para la app Empresa e Inventario
    #Puedes ver mis movidas en https://github.com/konguele' > /etc/motd"
    
    config.vm.define :db do |db|
    db.vm.box = "generic/rhel8"
    db.vm.hostname = "app_db.stilu-games.com"
    bd.vm.network :private_network, ip: "192.168.56.105"
    db.vm.provider :virtualbox do |vb|
    vb.memory = 2068
    vb.cpus = 1
    vb.name = "db_app"
    end
    end
    
    config.vm.define :web do |web|
    web.vm.hostname = "web.stilu-games.com"
    web.vm.box = "generic/rhel8"
    web.vm.network :private_network, ip: "192.168.56.106"
    web.vm.provider :virtualbox do |vb|
    vb.memory = 2068
    vb.cpus = 1
    vb.name = "web_server"
    end
    end
    end
  